# ---------------------------------
# Globals / defaults
install:
  - pip install --upgrade setuptools
  - python setup.py install
  - python -c "import sys; print(sys.path)"
before_script:
  - sudo rm -f /etc/boto.cfg
branches:
  only:
    - dev
# ---------------------------------
# Specify job grid
jobs:
  include:
    # ---------------------------------
    - name: Unit tests (Linux)
      language: python
      python: 3.7
      os: linux
      script:
        - pytest --disable-pytest-warnings daps_utils/tests/
    - name: Unit tests (OSX)
      language: python
      python: 3.7
      os: osx
      script:
        - pytest --disable-pytest-warnings daps_utils/tests/        
    # ---------------------------------
    - name: Script tests (Linux)
      language: python
      python: 3.7      
      os: linux
      script:
        - bash ./.travis/test_scripts.sh
    - name: Script tests (OSX)
      language: python
      python: 3.7      
      os: osx
      script:
        - bash ./.travis/test_scripts.sh        
    # ---------------------------------
    # - name: Integration
    #   script:
    #     - pytest --disable-pytest-warnings daps_utils/flows/tests/
