# ---------------------------------
# Globals / defaults
os:
  - linux
  - osx
install:
  - pip install --user --upgrade setuptools
  - python setup.py install
  - python -c "import sys; print(sys.path)"
before_script:
  - sudo rm -f /etc/boto.cfg
branches:
  only:
    - dev
# ---------------------------------
# Specify job grid
jobs:
  include:
    # ---------------------------------
    - name: Unit tests
      language: python
      python: 3.8      
      script:
        - pytest --disable-pytest-warnings daps_utils/tests/
    # ---------------------------------
    - name: Script tests
      language: bash
      script:
        - bash ./.travis/test_scripts.sh
    # ---------------------------------
    # - name: Integration
    #   script:
    #     - pytest --disable-pytest-warnings daps_utils/flows/tests/
