# ---------------------------------
# Globals / defaults
dist: xenial
os: linux
addons:
  apt:
    sources:
      - docker-xenial
cache: pip
install:
  - pip install --upgrade setuptools
  - python setup.py install
  - python -c "import sys; print(sys.path)"
before_script:
  - sudo rm -f /etc/boto.cfg
env:
  - AWS_ACCESS_KEY_ID='dummy'
    AWS_SECRET_ACCESS_KEY='dummy'
    AWS_DEFAULT_REGION='dummy'
branches:
  only:
    - dev
# ---------------------------------
# Specify job grid
jobs:
  include:
    # ---------------------------------
    - name: Unit tests (Linux)
      language: python
      python: 3.7
      script:
        - pytest -x daps_utils/tests/
    # ---------------------------------
    - name: Script tests (Linux)
      language: python
      python: 3.7
      script:
        - bash ./.travis/test_scripts.sh
    # ---------------------------------
    - name: Integration (Linux)
      language: python
      python: 3.7      
      script:
        - pytest -s -v -x daps_utils/flows/tests/integration/
